fixtures:
  symlinks:
    sssd: "#{source_dir}"
  forge_modules:
    augeasproviders_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.6.0"
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "3.0.1"
    datacat:
      repo: "richardc/datacat"
      ref: "0.6.2"
    dbus:
      repo: "bodgit/dbus"
      ref: "2.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "7.1.0"
